### ISSUE TITLE
Logs too verbose

### ISSUE THREAD

**Issue by jeffbakerexpedia** [ExpediaDotCom/haystack-secrets-commons#15]
The 1.0.9 version of haystack-secrets-commons logs the secrets detected within the past hour; this "past hour" calculation comes from the code that attempts to read S3 to update the whitelist. In a production environment, the number of secrets detected is quite large, and the large log line is not very useful. Just log the count of distinct secrets detected instead.

**Comment by shreyaa-sharma** [comment]
Done and closing this.
